name: angsd-snakemake-pipeline

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core packages for workflow
  - python =3.10.*
  - snakemake-minimal =7.18.*
  - mamba
  - pandas
  - graphviz
  - perl
  - gzip
  - pygments