name: landscape-genomics

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core packages for workflow
  - python >=3.7
  - snakemake-minimal >=6.13.1
  - mamba
  - pandas
  - graphviz