name: angsd-snakemake-pipeline

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core packages for workflow
  - python =3.11.*
  - snakemake-minimal =7.25.*
  - pandas =2.0.1
  - mamba
  - graphviz
  - pygments