name: landscape-genomics

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core packages for workflow
  - python >=3.9
  - snakemake-minimal >=7.6.2
  - mamba
  - pandas
  - graphviz
  - perl
  - gzip