site_name: ANGSD Snakemake Pipeline
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: config.md
  - Tutorial: tutorial.md
theme:
  name: material
  icon:
    repo: simple/github
    admonition:
      note: octicons/tag-16
  features:
    - search.highlight
repo_url: https://github.com/zjnolen/angsd-snakemake-pipeline
repo_name: zjnolen/angsd-snakemake-pipeline
plugins:
  - search
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true