site_name: ANGSD Snakemake Pipeline
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: config.md
  - Tutorial: tutorial.md
  - About: about.md
repo_url: https://www.github.com/zjnolen/angsd-snakemake-pipeline
theme: material
  icon:
    repo: material/github
plugins:
  - search
extra:
  version:
    provider: mike