site_name: PopGLen
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Configuration: config.md
  - Config cheat sheet: config-cheat.md
  - Tutorial: tutorial.md
  - Cluster execution: cluster-execution.md
  - Setting job resources: resources.md
  - Output file path overview: outfile-summ.md
theme:
  name: material
  icon:
    repo: simple/github
    admonition:
      note: octicons/tag-16
      question: octicons/question-16
  features:
    - toc.integrate
    - search.highlight
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
repo_url: https://github.com/zjnolen/PopGLen
repo_name: zjnolen/PopGLen
plugins:
  - search
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true