__default__:
  # complete with SLURM account ID jobs should be run on
  account: snic2021-5-599
  
  # default time for a job if this should be different than cluster default
  time: 01:00:00

  # directories for slurm logs (inside project directory)
  output: "slurm/logs/{rule}/{rule}.{wildcards}.out"