#=====================Dataset Configuration============================#

samples: config/samples.tsv

units: config/units.tsv

dataset: "dataset_name"

#===================== Reference Configuration ========================#

chunk_size:

reference:
  name: "ref_name"
  fasta: "path/to/ref.fa"
  mito: []
  sex-linked: []
  exclude: []
  min_size:

#===================== Sample Set Configuration =======================#

exclude_ind: []

excl_pca-admix: []

#==================== Downsampling Configuration ======================#

downsample_cov:

#====================== Analysis Selection ============================#

populations: []

analyses:
  # filtering
  genmap: true
  repeatmasker:
    local_lib:
    dfam_lib:
    build_lib: true
  extreme_depth:
    median: [0.5, 1.5]
    quantile:
  dataset_missing_data: 0.8
  population_missing_data: 0.8
  # quality control
  qualimap: true
  damageprofiler: true
  endogenous_content: true
  # population genomic analyses
  estimate_ld: false
  ld_decay: false
  pca_pcangsd: false
  admix_ngsadmix: false
  relatedness: 
    ngsrelate: false
    waples2019: false
  thetas_angsd: false
  heterozygosity_angsd: false
  fst_angsd:
    populations: false
    individuals: false
  inbreeding_ngsf-hmm: false
  ibs_matrix: false

#=========================== Filter Sets ==============================#

filter_beds:
  example:

only_filter_beds: false

#===================== Software Configuration =========================#

mapQ: 30
baseQ: 30

params:

  genmap:
    K: "100"
    E: "2"
    map_thresh: 1
  fastp:
    extra: "-p -g --overlap_len_require 15"
  picard:
    MarkDuplicates: "--REMOVE_DUPLICATES true --OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500"
  angsd:
    gl_model: 2 # gl_model - 1=SAMtools, 2=GATK, 3=SOAPsnp, 4=SYK
    maxdepth: 1000
    extra: "-C 50 -uniqueOnly 1"
    snp_pval: "1e-6"
    min_maf: 0.05
  ngsld:
    max_kb_dist_est-ld: 4000
    max_kb_dist_decay: 100
    max_kb_dist_pruning: 100
    rnd_sample_est-ld: 0.001
    rnd_sample_decay: 0.001
    fit_LDdecay_extra: "--fit_level 100 --fit_boot 100 --plot_size 3,6 --plot_data --plot_no_legend --plot_y_lim 0.5"
    fit_LDdecay_n_correction: true
    pruning_min-weight: 0.1
  realsfs:
    fold: 1 # Should only be set to 1 for now
    sfsboot: 100
  fst:
    whichFst: 1
    win_size: 50000
    win_step: 10000
  thetas:
    win_size: 50000
    win_step: 10000
    minsites: 1000
  ngsadmix:
    kvalues: [1,2,3,4]
    reps: 100
    minreps: 20
    thresh:
    conv:
    extra: "-maxiter 4000"
  ibs:
    doibs: 1