#=====================Dataset Configuration============================#

samples: config/samples_pargus.tsv

units: config/units.tsv

dataset: "pargus"

#===================== Output Configuration ===========================#

paths:
  # main base folder for results - dataset will be appended to end
  results: "results"
  # folder where intermediate files will be stored - dataset will be 
  # appended to end
  intermediate: "intermediate"
  # folder where log files will be stored - dataset will be appended to 
  # end
  logs: "logs"

#===================== Reference Configuration ========================#

# `fasta` should be a string with the absolute or relative path to a
# local copy of the fasta or a URL to a online location it will be 
# downloaded from.
# `mito` should be the ID (string format) of the mitochondria in the 
# reference to be isolated for mitochondrial analyses and removed in 
# nuclear ones
# `excl_chr` should be a list of strings referring to chromosome IDs 
# that you want excluded from autosomal analyses - these may be sex 
# chromosomes, unidentified contigs, etc.
reference: 
#: "https://darwin.cog.sanger.ac.uk/insects/Polyommatus_icarus/ilPolIcar1/assemblies/working/20200120.hicanu.purge/20200120.hicanu.purge.prim.fasta.gz"
  fasta: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/905/404/155/GCA_905404155.1_ilPleArgu1.1/GCA_905404155.1_ilPleArgu1.1_genomic.fna.gz"
  mito: "FR989949.1"
  excl_chr: ["FR989932.1","CAJQEX010000004.1","CAJQEX010000013.1","CAJQEX010000014.1","CAJQEX010000015.1","CAJQEX010000002.1","CAJQEX010000005.1","CAJQEX010000006.1","CAJQEX010000009.1","CAJQEX010000007.1","CAJQEX010000003.1","CAJQEX010000008.1","CAJQEX010000010.1","CAJQEX010000001.1","CAJQEX010000011.1","CAJQEX010000012.1"]

#==================== Downsampling Configuration ======================#

downsample_cov:

#====================== Analysis Selection ============================#
# Here you select what steps in the pipeline you would like to perform.

analyses:
  # raw data and mapping quality control
  pretrim_fastqc: true
  posttrim_fastqc: true
  endoCont_endorspy: true
  qualimap: true
  # population genomic analyses
  pca_pcangsd: true
  admix_ngsadmix: true
  thetas_angsd: true
  heterozygosity_angsd: true
  inbreedingCoeff_ngsf-hmm: true
  ROH_ngsf-hmm: true
  pastNe_gone: true

#===================== Software Configuration =========================#

params:
  picard:
    # By default we set Picard to remove duplicate reads, change to 
    # false to flag only.
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  angsd:
    # gl_model - 1=SAMtools, 2=GATK, 3=SOAPsnp, 4=SYK; default is 1
    gl_model: 1
    # max_missing - Exclude sites based on missing data in individuals 
    # where 0.0 allows sites with completely missing data and 1.0 
    # permits no missing data. You have the option to set different 
    # values for the dataset as a whole (such as for making a PCA) and 
    # for individual populations (calculating thetas, F, ROH, etc.). We 
    # set the default to 0.2 (20% missing data) for populations and 0.0 
    # for the whole dataset.
    max_missing_pop: 0.2
    max_missing_dataset: 0.0
    # min_depth_mult - A multiplier to define the minimum depth to include a 
    # site in an analysis, it is multiplied by the average depth. A hard coded 
    # minimum depth of 3 per individual is always included.
    min_depth_mult: 0.33
    # max_depth_mult - A multiplier to define the maximum depth to include a 
    # site in an analysis, it is multiplied by the average depth.
    max_depth_mult: 3
    # extra - any additional filtering parameters to be used across all 
    # analyses with angsd. By default, we use -C 50 to correct for 
    # excessive mismatches, set a min mapping quality of 30, a minimum 
    # base quality of 20, permit both paired reads and singletons 
    # (needed since we mapped both merged and unmerged reads), remove 
    # reads with multiple best hits, and reducing base quality scores 
    # based on baq (penalizes mapping around indels)
    extra: "-C 50 -minMapQ 30 -minQ 20 -only_proper_pairs 0 -uniqueOnly 1 -baq 1"
    # fold - Define if SFS should be folded when made. If you don't 
    # have ancestral states to assign to -anc, it is best to set to 1. 
    # We set the default to 1.
    fold: 1
    # sfsboot - Define number of bootstrap SFS to produce, we default 
    # to 100.
    sfsboot: 100
    snp_pval: "1e-6"
    min_maf: 0.05
  ngsadmix:
    kvalues: [2,3,4,5]