#=====================Dataset Configuration============================#

samples: config/samples.tsv

units: config/units.tsv

dataset: "test"

#===================== Reference Configuration ========================#

chunk_size: 200000

reference:
  name: "testref"
  fasta: "data/ref/testref.fa"
  mito: ["chrM"]
  sex-linked: ["chrZ"]
  exclude: []
  min_size: 3000
#===================== Sample Set Configuration =======================#

exclude_ind: []

excl_pca-admix: []

#==================== Downsampling Configuration ======================#

downsample_cov:

#====================== Analysis Selection ============================#

populations: []

analyses:
  # filtering
  genmap: true
  repeatmasker:
    local_lib:
    dfam_lib:
    build_lib: true
  extreme_depth: true
  dataset_missing_data: 0.5
  population_missing_data: 0.5
  # quality control
  qualimap: true
  damageprofiler: true
  endogenous_content: true
  # population genomic analyses
  pca_pcangsd: true
  admix_ngsadmix: true
  relatedness: 
    ngsrelate: true
    waples2019: true
  thetas_angsd: true
  heterozygosity_angsd: true
  fst_angsd:
    populations: true
    individuals: true
  inbreeding_ngsf-hmm: true
  ibs_matrix: true

#===================== Software Configuration =========================#

mapQ: 30
baseQ: 30

params:
  genmap:
    K: "100"
    E: "2"
    map_thresh: 1
  fastp:
    extra: "-p -g --overlap_len_require 15"
  picard:
    MarkDuplicates: "--REMOVE_DUPLICATES true --OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500"
  angsd:
    gl_model: 2 # gl_model - 1=SAMtools, 2=GATK, 3=SOAPsnp, 4=SYK
    maxdepth: 1000
    extra: "-C 50 -uniqueOnly 1"
    snp_pval: "1e-6"
    min_maf: 0.05
  realsfs:
    fold: 1 # Should only be set to 1 for now
    sfsboot: 100
  fst:
    whichFst: 1
    win_size: 50000
    win_step: 10000
  thetas:
    win_size: 50000
    win_step: 10000
  ngsadmix:
    kvalues: [1,2,3,4]
    reps: 100
    minreps: 20
    thresh:
    conv:
    extra: "-maxiter 4000"
  ibs:
    doibs: 1