#=====================Dataset Configuration============================#

samples: config/samples.tsv

units: config/units.tsv

dataset: "test"

#===================== Reference Configuration ========================#

chunk_size: 200000

reference:
  name: "testref"
  fasta: "data/ref/testref.fa"
  mito: ["chrM"]
  sex-linked: ["chrZ"]
  exclude: []
  min_size: 3000

#===================== Sample Set Configuration =======================#

exclude_ind: []

excl_pca-admix: []

#==================== Downsampling Configuration ======================#

downsample_cov:

#====================== Analysis Selection ============================#

populations: []

analyses:
  # mapping options
  mapping:
    historical_only_collapsed: true
  # filtering
  pileup-mappability: true
  repeatmasker:
    local_lib:
    dfam_lib:
    build_lib: true
  extreme_depth: true
  dataset_missing_data: 0.5
  population_missing_data: 0.5
  # quality control
  qualimap: true
  damageprofiler: true
  mapdamage_rescale: true
  # population genomic analyses
  estimate_ld: true
  ld_decay: true
  pca_pcangsd: true
  admix_ngsadmix: true
  relatedness: 
    ngsrelate: true
    ibsrelate_ibs: true
    ibsrelate_sfs: true
  thetas_angsd: true
  heterozygosity_angsd: true
  fst_angsd:
    populations: true
    individuals: true
  inbreeding_ngsf-hmm: true
  ibs_matrix: true

#=========================== Filter Sets ==============================#

filter_beds:
  example: "config/example-filt.bed"
  badexample: "config/badexample-filt.bed"

only_filter_beds: false

#===================== Software Configuration =========================#

mapQ: 30
baseQ: 30

params:
  clipoverlap:
    clip_user_provided_bams: true
  genmap:
    K: "100"
    E: "2"
    map_thresh: 1
  extreme_depth_filt:
    method: "median"
    bounds: [ 0.5, 1.5 ]
    filt-on-dataset: true
    filt-on-depth-classes: true
  fastp:
    extra: "-p -g" # don't put --merge or --overlap_len_require here, they're implicit
    min_overlap_mod: 30
    min_overlap_hist: 15
  picard:
    MarkDuplicates: "--REMOVE_DUPLICATES true --OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500"
  angsd:
    gl_model: 2 # gl_model - 1=SAMtools, 2=GATK, 3=SOAPsnp, 4=SYK
    maxdepth: 1000
    extra: ""
    extra_saf: ""
    extra_beagle: ""
    snp_pval: "1e-6"
    min_maf: 0.05
  ngsld:
    max_kb_dist_est-ld: 200
    max_kb_dist_decay: 100
    max_kb_dist_pruning: 50
    rnd_sample_est-ld: 0.001
    rnd_sample_decay: 0.9
    fit_LDdecay_extra: "--fit_level 3"
    fit_LDdecay_n_correction: true
    pruning_min-weight: 0.1
  realsfs:
    fold: 1 # Should only be set to 1 for now
    sfsboot: 100
  fst:
    whichFst: 1
    win_size: 10000
    win_step: 5000
  thetas:
    win_size: 10000
    win_step: 5000
    minsites: 1000
  ngsadmix:
    kvalues: [1,2,3,4]
    reps: 100
    minreps: 20
    thresh:
    conv:
    extra: "-maxiter 4000"
  ibs:
    doibs: 1