name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches_ignore: []
    paths-ignore:
      - '**/*.md'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3.5.2
    - name: Formatting
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        snakefile: "workflow/Snakefile"
        args: "--lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 1024
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Checkout repository
      uses: actions/checkout@v3.5.2
    - name: Set up conda environment and singularity
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml
        create-args: >-
          apptainer
    - name: Test workflow
      shell: bash -l {0}
      run: |
        mkdir -p temp
        workdir=$(pwd -P)
        TMPDIR=$workdir/temp
        snakemake --directory .test --configfile .test/config/config.yaml --config samples=config/samples_testSRA.tsv --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --use-singularity --default-resources mem_mb=1000 --until fastp_mergedout
        snakemake --directory .test --configfile .test/config/config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --use-singularity --default-resources mem_mb=1000
    - name: Test report
      shell: bash -l {0}
      run: |
        snakemake --directory .test --configfile .test/config/config.yaml --cores 2 --report report.html
